(source gnu)
(source melpa)

(depends-on "rainbow-delimiters")
(depends-on "cask")
(depends-on "company")
(depends-on "sbt-mode")
(depends-on "scala-mode")
(depends-on "haskell-mode")
(depends-on "js2-mode")
(depends-on "yaml-mode")
(depends-on "web-mode")

